# Generated by Django 3.1.5 on 2021-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=512, unique=True)),
                ('long_url', models.TextField(unique=True)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
