# Generated by Django 3.1.5 on 2021-01-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20210112_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
